name: Java CI - Maven Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compiler le code avec Maven
        working-directory: rest-api
        run: mvn clean compile
      
      - name: Executer les tests avec Maven
        working-directory: rest-api
        run: mvn test